### ISSUE TITLE
eaccess permission denied when trying to use yo

### ISSUE THREAD

**Issue by allenwzj** [yeoman/yeoman.io#282]
eaccess permission denied when trying to use yo

root@precise64:~/local# yo
[?] 'Allo root! What would you like to do? (Use arrow keys)
‣ Install a generator
  Find some help
  Get me out of here!
/usr/lib/node_modules/yo/node_modules/insight/node_modules/configstore/configstore.js:66
                                throw err;
                                      ^
Error: EACCES, permission denied '/root/.config/configstore/insight-yo.yml'
You don't have access to this file.

```
at Object.fs.openSync (fs.js:432:18)
at Object.fs.writeFileSync (fs.js:971:15)
at Object.create.all.set (/usr/lib/node_modules/yo/node_modules/insight/node_modules/configstore/configstore.js:56:8)
at Object.Configstore (/usr/lib/node_modules/yo/node_modules/insight/node_modules/configstore/configstore.js:19:11)
at new Insight (/usr/lib/node_modules/yo/node_modules/insight/lib/insight.js:23:34)
at process.<anonymous> (/usr/lib/node_modules/yo/node_modules/insight/lib/push.js:11:16)
at process.emit (events.js:98:17)
at handleMessage (child_process.js:322:10)
at Pipe.channel.onread (child_process.js:349:11)
```

Thank you in advance.

**Comment by igoreliasm** [comment]
try the procedure:
```
echo prefix = ~/.node >> ~/.npmrc
export PATH=$HOME/.node/bin:$PATH
```

**Comment by paulobar** [comment]
@md5 I subscribe to your view. Using an arbitrary user id is problematic. And solemnly swear that I shall never again run Yeoman as root. Thank you all.

**Comment by walkerwzy** [comment]
@igoreliasm it works for me, tks

**Comment by DantewithZYX** [comment]
.config was missing for me too. (on Mac) Turned out the owner of my /Users/*MyName*/ folder was not the user I had installed node and npm with, who had ownership of those files. Once I logged into the other user on my mac who actually had ownership of the root directory /Users/*MyName*/ and reinstalled everything fresh, it worked great. Could have probably logged in as root and changed the owner of my root folder on my initial account but switching to the other user is fine too. Make sure you cd /Users/ and ls -l and make sure the user you're installing with is actually the owner of your root directory. 

Stupid mac problem, because I had to create new user when I got my new mac, even tho I migrated my previous user from my old mac and normally use that. But this new user I've never actually used before had ownership of my normal account's root directory..took way to long to figure out. This thread did help tho! Thanks!

**Comment by estani** [comment]
It took me a while to figure out, but:

`npm -g install yo` will install the module in /usr/local/lib/node_modules/ (so you need root rights for this)

calling yo will create some config files in $HOME/.config/configstore/* (for user tracking, etc)
and there's the requirement that $HOME must be owned by any user but root.

So for docker: install normally and add a user and set $HOME to that user home at the end of your Dockerfile.

**Comment by mandb** [comment]
Just make the folder "configstore" it's looking for... 

>  yo -v
Error: EACCES, permission denied '/root/.config/configstore/insight-yo.yml'
You don't have access to this file.

    at Object.fs.openSync (evalmachine.<anonymous>:439:18)
    at Object.fs.readFileSync (evalmachine.<anonymous>:290:15)
    at Object.create.all.get (/usr/lib/node_modules/yo/node_modules/configstore/index.js:34:29)
    at Object.Configstore (/usr/lib/node_modules/yo/node_modules/configstore/index.js:27:44)
    at new Insight (/usr/lib/node_modules/yo/node_modules/insight/lib/index.js:26:34)
    at Object.<anonymous> (/usr/lib/node_modules/yo/cli.js:123:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)


> mkdir /root/.config/configstore
> chmod g+rwx /root /root/.config /root/.config/configstore

> yo -v
1.3.3

**Comment by SBoudrias** [comment]
@mandb `yo` only fallback to a safe uid if you run yo as sudo.

**Comment by mandb** [comment]
Perhaps it could fail more elegantly if run as root, some verbose maybe?

**Comment by SBoudrias** [comment]
@mandb that's what we had before and people complained, so we made this fix and it's been better since.

**Comment by mandb** [comment]
Wrong side of the fence I guess!  :+1:

**Comment by OKNoah** [comment]
I had this error as well and fixed it by making a new user and not running `yo generator-hubot` with sudo. But at the end of the hub configuration it fails and says I should run again as root.

	npm ERR! Error: EACCES, mkdir '/home/my-user/.npm/commander/1.3.2'
	npm ERR!  { [Error: EACCES, mkdir '/home/my-user/.npm/commander/1.3.2']
	npm ERR!   errno: 3,
	npm ERR!   code: 'EACCES',
	npm ERR!   path: '/home/my-user/.npm/commander/1.3.2',
	npm ERR!   parent: 'express' }
	npm ERR!
	npm ERR! Please try running this command again as root/Administrator.

Maybe this is more of an npm issue now?

**Comment by OKNoah** [comment]
Found solution here: https://github.com/krakenjs/generator-kraken/issues/114#issuecomment-54201366

**Comment by atomi** [comment]
@SBoudrias Yours is a bad solution. It creates problems for people that know what they're doing Yeoman should block root altogether unless a command line flag is set. Do not change UID, especially without even telling the user.

By the way, it's generally safe to run as root in containers.

**Comment by passy** [comment]
@atomi Since we put that safe-guard in place, we've dramatically reduced the number of cases where people would completely screw their system. We want Yeoman to approachable as possible by newcomers and hence this choice is a very important and effective one.

At least for Docker containers it's easy enough to run commands in a user context.

**Comment by atomi** [comment]
@passy Yeah. It's incredibly inconvenient [1] and it won't work if the mounted project directory is a different user. Which means you now have to change the Dockerfile to match the uid of your project so Docker pull won't automatically work. 

Bower does a good job at handling the issue with ```--allow-root``` you can do that.
