### ISSUE TITLE
Artwork used with no attribution 

### ISSUE THREAD

**Issue by vladikoff** [yeoman/yeoman.io#452]
via http://www.unixstickers.com/about-unixstickers

![image](https://cloud.githubusercontent.com/assets/128755/7049131/41600d98-dde5-11e4-925b-0f9a6fa27ff0.png)

Not sure if you guys care about this, feel free to close.

**Comment by sindresorhus** [comment]
https://twitter.com/sindresorhus/status/585847932923969536

**Comment by Facens** [comment]
@sindresorhus @vladikoff I represent unixstickers, image removed and a deep sorry for our mistake.

We can either:
- Remove it completely if you don't like the artwork to be used there
- Specify the attribution in the page

Note: we're launching Yeoman stickers soon, that's why we got excited with using the artwork, it was an excess of enthusiasm : )

**Comment by Facens** [comment]
Addendum: of course if a Yeoman rep is OK with our use of the artwork, we're happy to re-include the image. The license of the artworks is BSD which technically allows this kind of use, but until we clear this out the right choice was to remove the artwork ASAP, reason why we acted promptly and won't re-enable if there isn't explicit permission : )

**Comment by sindresorhus** [comment]
No worries :)

The license is CC 4.0: https://github.com/yeoman/yeoman.io/blob/8bb892532a8af7dd925b0e0a3b6b0f56409b2a3b/media/readme.md

Feel free to use it with attribution.

**Comment by SBoudrias** [comment]
I mean, you're free to use without attribution because we don't want to run people and because we're okay with companies using our logo to sell classes or provide stickers without our explicit agreement.

But I mean, it'd be tricky if a company used our logo as theirs or used our logo to make themselves pass as the yeoman team or whatev.

As long as the use is reasonable we're happy about it. This use case seems reasonable to me, but if unixsticker was to use our artworks everywhere on their site, then it'd be more problematic.

**Comment by sindresorhus** [comment]
I've moved the artwork into a separate repo to make the license clearer: https://github.com/yeoman/media
